Bugfix: Ensure datamap & contents are mutable. (#51)
We encountered an exception in production @ Coursera regarding
a problem with immutable components of the data maps. Because we
do deep processing, we need to ensure that everything is mutable.
This commit recursively checks the tree and ensures that it is
mutable.

Exception found in production @ Coursera:

java.lang.UnsupportedOperationException: Cannot mutate a read-only map
        at com.linkedin.data.collections.CheckedMap.checkMutability(CheckedMap.java:298) ~[com.linkedin.pegasus.data-3.1.1.jar:na]
        at com.linkedin.data.collections.CheckedMap.clear(CheckedMap.java:158) ~[com.linkedin.pegasus.data-3.1.1.jar:na]
        at org.coursera.pegasus.TypedDefinitionHandler.convertFromPegasus(TypedDefinitionHandler.java:69) ~[org.coursera.naptime.naptime-pegasus-0.1.0.jar:0.1.0]
        at org.coursera.pegasus.TypedDefinitionDataCoercer$TypedDefinitionFromPegasusVisitor.visit(TypedDefinitionDataCoercer.java:79) ~[org.coursera.naptime.naptime-pegasus-0.1.0.jar:0.1.0]
        at org.coursera.pegasus.TypedDefinitionDataCoercer.visitUnionTyperefs(TypedDefinitionDataCoercer.java:207) ~[org.coursera.naptime.naptime-pegasus-0.1.0.jar:0.1.0]
        at org.coursera.pegasus.TypedDefinitionDataCoercer.visitUnionTyperefs(TypedDefinitionDataCoercer.java:186) ~[org.coursera.naptime.naptime-pegasus-0.1.0.jar:0.1.0]
        at org.coursera.pegasus.TypedDefinitionDataCoercer.visitUnionTyperefs(TypedDefinitionDataCoercer.java:228) ~[org.coursera.naptime.naptime-pegasus-0.1.0.jar:0.1.0]
        at org.coursera.pegasus.TypedDefinitionDataCoercer.visitUnionTyperefs(TypedDefinitionDataCoercer.java:186) ~[org.coursera.naptime.naptime-pegasus-0.1.0.jar:0.1.0]
        at org.coursera.pegasus.TypedDefinitionDataCoercer.convertUnionToTypedDefinitionInPlace(TypedDefinitionDataCoercer.java:116) ~[org.coursera.naptime.naptime-pegasus-0.1.0.jar:0.1.0]
        at org.coursera.naptime.actions.RestActionCategoryEngine2$$anonfun$serializeCollection$1$$anonfun$apply$4.apply(RestActionCategoryEngine2.scala:143) ~[org.coursera.naptime.naptime_2.11-0.1.0.jar:0.1.0]
        at org.coursera.naptime.actions.RestActionCategoryEngine2$$anonfun$serializeCollection$1$$anonfun$apply$4.apply(RestActionCategoryEngine2.scala:142) ~[org.coursera.naptime.naptime_2.11-0.1.0.jar:0.1.0]
        at scala.Option.foreach(Option.scala:257) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at org.coursera.naptime.actions.RestActionCategoryEngine2$$anonfun$serializeCollection$1.apply(RestActionCategoryEngine2.scala:142) ~[org.coursera.naptime.naptime_2.11-0.1.0.jar:0.1.0]
        at org.coursera.naptime.actions.RestActionCategoryEngine2$$anonfun$serializeCollection$1.apply(RestActionCategoryEngine2.scala:130) ~[org.coursera.naptime.naptime_2.11-0.1.0.jar:0.1.0]
        at scala.collection.immutable.List.foreach(List.scala:381) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at org.coursera.naptime.actions.RestActionCategoryEngine2$.serializeCollection(RestActionCategoryEngine2.scala:130) ~[org.coursera.naptime.naptime_2.11-0.1.0.jar:0.1.0]
        at org.coursera.naptime.actions.RestActionCategoryEngine2$.org$coursera$naptime$actions$RestActionCategoryEngine2$$buildResponse(RestActionCategoryEngine2.scala:243) ~[org.coursera.naptime.naptime_2.11-0.1.0.jar:0.1.0]
        at org.coursera.naptime.actions.RestActionCategoryEngine2$$anon$6$$anonfun$mkResponse$6.apply(RestActionCategoryEngine2.scala:403) ~[org.coursera.naptime.naptime_2.11-0.1.0.jar:0.1.0]
        at org.coursera.naptime.actions.RestActionCategoryEngine2$$anon$6$$anonfun$mkResponse$6.apply(RestActionCategoryEngine2.scala:402) ~[org.coursera.naptime.naptime_2.11-0.1.0.jar:0.1.0]
        at org.coursera.naptime.actions.RestActionCategoryEngine2$.org$coursera$naptime$actions$RestActionCategoryEngine2$$mkOkResponse(RestActionCategoryEngine2.scala:64) ~[org.coursera.naptime.naptime_2.11-0.1.0.jar:0.1.0]
        at org.coursera.naptime.actions.RestActionCategoryEngine2$$anon$6.mkResponse(RestActionCategoryEngine2.scala:402) ~[org.coursera.naptime.naptime_2.11-0.1.0.jar:0.1.0]
        at org.coursera.naptime.actions.RestAction$$anonfun$apply$3$$anonfun$apply$7$$anonfun$apply$9$$anonfun$1$$anonfun$apply$10$$anonfun$org$coursera$naptime$actions$RestAction$class$$anonfun$$anonfun$$anonfun$$anonfun$$anonfun$$run$1$2.apply(RestAction.scala:115) ~[org.coursera.naptime.naptime_2.11-0.1.0.jar:0.1.0]
        at org.coursera.naptime.actions.RestAction$$anonfun$apply$3$$anonfun$apply$7$$anonfun$apply$9$$anonfun$1$$anonfun$apply$10$$anonfun$org$coursera$naptime$actions$RestAction$class$$anonfun$$anonfun$$anonfun$$anonfun$$anonfun$$run$1$2.apply(RestAction.scala:114) ~[org.coursera.naptime.naptime_2.11-0.1.0.jar:0.1.0]
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.util.Try$.apply(Try.scala:192) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.util.Success.map(Try.scala:237) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        ... 14 common frames omitted